name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*.*.*"

jobs:
  build_release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Build python script
        run: |
          pip install -r requirements.txt --user
          pip install -r pyinstaller --user
      - run: pyinstaller --onefile snyk-sast-tag.py
      - uses: actions/upload-artifact@v4
        with:
          name: snyk-sast-tag
          path: ./dist/snyk-sast-tag
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/snyk-sast-tag
