name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*.*.*"

jobs:
  build_release:
    name: Create Release
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    strategy:
      fail-fast: true
      matrix:
        os: ['windows-latest', 'ubuntu-latest', 'macos-latest']
        python-version: ['3.10']
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - run: pyinstaller --onefile snyk-sast-tag.py --name snyk-sast-tag-${{ runner.os }}
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./dist/*
